custom-select-box
NextGenDevOrg/02-CSS-Learning pull request #10
Opened 2021-10-24 09:08 UTC by mujeeb100

2021-10-30 09:32 UTC, faran4engg requested changes
correct folder name 😒 here too

2021-10-31 09:09 UTC, coder-mezab approved these changes

2021-10-31 09:44 UTC, AbbasShaikh0304 requested changes

2021-10-31 09:44 UTC, AbbasShaikh0304 commented on tasks-by-users/muzeeb100/Custom Select Box css/style.css
> +    outline: none;
```suggestion
    background: #0563af;
    color: #fff;

    width: 250px;
    height: 50px;
    padding: 10px;

    font-size: 20px;

    border: none;
    box-shadow: 0 5px 25px rgba(0,0,0,.5);
    outline: none;

    -webkit-appearance: button;
```

2021-10-31 09:51 UTC, AbbasShaikh0304 commented on tasks-by-users/muzeeb100/Custom Select Box css/style.css
> +    outline: none;
Group Similar Properties so it will look more clear

2021-11-13 14:21 UTC, AbbasShaikh0304 commented on tasks-by-users/muzeeb100/Custom Select Box css/style.css
> +    outline: none;
????

2021-12-24 07:02 UTC, merged