Added Card Hover Effect files
NextGenDevOrg/02-CSS-Learning pull request #18
Opened 2021-10-31 07:01 UTC by shaikh-7abish

2021-10-31 09:07 UTC, coder-mezab commented on tasks-by-users/shaikh-7abish/04-card-hover-effect/main.css
> +    border-radius: 5px;
grp these properties @shaikh-7abish

2021-10-31 09:08 UTC, coder-mezab commented on tasks-by-users/shaikh-7abish/04-card-hover-effect/main.css
> +    transform: translateY(-12rem);
group similar properties

2021-10-31 09:11 UTC, anask601 approved these changes

2021-10-31 09:52 UTC, AbbasShaikh0304 approved these changes

2021-10-31 10:01 UTC, narayand16 approved these changes

2021-10-31 11:04 UTC, faran4engg commented on tasks-by-users/shaikh-7abish/04-card-hover-effect/main.css
> +body{
looks like `prettier` is not configured

2021-10-31 11:05 UTC, faran4engg requested changes
Let's fix these comments !

2021-11-01 06:19 UTC, AlishaPrasad approved these changes

2021-11-01 06:20 UTC, faran4engg commented
Live demo link ?

2021-11-01 06:22 UTC, faran4engg approved these changes

2021-11-01 06:22 UTC, faran4engg commented on tasks-by-users/shaikh-7abish/04-card-hover-effect/main.css
> +body{
Resolving conversation

2021-11-01 07:21 UTC, merged