Kiran-512
NextGenDevOrg/02-CSS-Learning pull request #56
Opened 2021-12-27 15:07 UTC by Kiran-512

Hi,

I have completed the portfolio with html and CSS. Please Review the JS code, it's creating trouble for me.

2021-12-27 15:10 UTC, faran4engg commented on assets/js/main.js
> +/*==================== MENU SHOW Y HIDDEN ====================*/
it looks like you haven't included it in HTML file :)

2021-12-28 07:31 UTC, Abbas4tech commented on index.html
> +          <img src="assets/img/about.jpg" alt="" class="about__img" />
alt ? @Kiran-512

2021-12-28 07:34 UTC, Abbas4tech commented on index.html
> +                  >Companies <br />
`<br/>` is this working?

2021-12-28 07:50 UTC, Abbas4tech requested changes
You had to create a new branch for every project @Kiran-512 !!!

2021-12-28 14:06 UTC, Kiran-512 commented on index.html
> +          <img src="assets/img/about.jpg" alt="" class="about__img" />
Noted and added alt now

2021-12-28 14:07 UTC, Kiran-512 commented on index.html
> +                  >Companies <br />
Yes, it worked.

2021-12-29 08:15 UTC, closed without merging