rectangle in the circle
NextGenDevOrg/02-CSS-Learning pull request #6
Opened 2021-10-20 14:24 UTC by mujeeb100

plesase review it small css task.

2021-10-20 17:35 UTC, shaikh-7abish approved these changes

2021-10-21 04:43 UTC, AlishaPrasad approved these changes

2021-10-30 09:31 UTC, faran4engg requested changes
correct folder name 😒

2021-10-31 11:07 UTC, faran4engg commented on tasks-by-users/muzeeb100/rectangle in the circle/style.css
> +  border: 5px solid black;
group properties

2021-10-31 11:07 UTC, faran4engg commented on tasks-by-users/muzeeb100/rectangle in the circle/style.css
> +  background-color: orange;
here too

2021-10-31 11:08 UTC, faran4engg commented
> lgtm

How come ? @Tauqeer-Ahmed-99 !
you overlooked css grouping + file name in the PR (name has spaces)

2021-12-23 22:22 UTC, nehalskdev approved these changes

2021-12-24 07:02 UTC, merged