Completed customized checkbox
NextGenDevOrg/02-CSS-Learning pull request #69
Opened 2022-01-02 06:46 UTC by Naufil-Shemle

**Give your valuable code review and approval as soon as possible.**

2022-01-02 12:32 UTC, fayez-baig commented on tasks-by-users/Naufil-Shemle/09-Checkbox/style.css
> +  /* position: relative; */
remove commented code

2022-01-02 12:33 UTC, fayez-baig requested changes
remove commented code

2022-01-02 12:36 UTC, Naufil-Shemle commented on tasks-by-users/Naufil-Shemle/09-Checkbox/style.css
> +  /* position: relative; */
Removed

2022-01-02 12:37 UTC, fayez-baig approved these changes

2022-01-03 07:08 UTC, rifaq-ahmer approved these changes

2022-01-03 13:46 UTC, mmusk approved these changes

2022-01-04 02:34 UTC, Rehan-Khan-Engineer approved these changes

2022-01-04 05:49 UTC, merged